package deon

import (
	"strconv"
	"strings"
)

// Leaflink extraction (specification 12). With leaflinks on, a map or list sitting at or below
// leaflinkLevel is lifted out of the root and written as its own declaration, and where it stood the
// root carries a link to it. It is a presentation of the same value — the extracted declarations plus
// the root that references them evaluate back to what was written — traded for a root that is flatter
// and a set of parts each addressable by name.

// leaflinkRef marks the place a container was lifted from. It is not a Deon value; it exists only
// between extraction and writing, so the writers below recognise it and emit a link where it stands.
type leaflinkRef struct {
	name string
}

type leaflinkDecl struct {
	name  string
	value Value
}

func stringifyWithLeaflinks(value Value, options StringifyOptions) string {
	root, decls := extractLeaflinks(value, options)

	var b strings.Builder
	if options.GeneratedHeader {
		b.WriteString("// Generated by Deon.\n\n")
	}
	if options.GeneratedComments {
		b.WriteString("// Root.\n\n")
	}
	writeValue(root, 0, options, &b)
	b.WriteByte('\n')

	for i, decl := range decls {
		b.WriteByte('\n')
		if options.GeneratedComments && i == 0 {
			b.WriteString("// Leaflinks.\n\n")
		}
		b.WriteString(writeKey(decl.name))
		b.WriteByte(' ')
		writeValue(decl.value, 0, options, &b)
		b.WriteByte('\n')
	}
	return b.String()
}

// extractLeaflinks walks the value and replaces every map or list at or below leaflinkLevel with a
// leaflinkRef, collecting the lifted containers as declarations. Once a container is lifted its
// descendants travel with it and are not separately lifted, so the walk does not recurse into a node
// it has extracted. The root itself (level 0) is never extracted.
func extractLeaflinks(value Value, options StringifyOptions) (Value, []leaflinkDecl) {
	level := options.LeaflinkLevel
	if level < 1 {
		level = 1
	}

	var decls []leaflinkDecl
	var walk func(v Value, depth int, path []string) Value
	walk = func(v Value, depth int, path []string) Value {
		_, isMap := v.(*Map)
		_, isList := v.([]Value)
		if (isMap || isList) && depth >= level {
			name := leaflinkName(path)
			decls = append(decls, leaflinkDecl{name: name, value: v})
			return &leaflinkRef{name: name}
		}

		switch container := v.(type) {
		case *Map:
			out := NewMap()
			for _, key := range container.Keys() {
				member, _ := container.Get(key)
				out.Set(key, walk(member, depth+1, appendSegment(path, key)))
			}
			return out
		case []Value:
			out := make([]Value, len(container))
			for i, item := range container {
				out[i] = walk(item, depth+1, appendSegment(path, strconv.Itoa(i)))
			}
			return out
		default:
			return v
		}
	}

	root := walk(value, 0, nil)
	return root, decls
}

func appendSegment(path []string, segment string) []string {
	out := make([]string, len(path)+1)
	copy(out, path)
	out[len(path)] = segment
	return out
}

// leaflinkName builds the root-relative name of a lifted container (specification 12): each path
// segment escapes `~` as `~0` and `/` as `~1`, and the segments join with `/`.
func leaflinkName(path []string) string {
	escaped := make([]string, len(path))
	for i, segment := range path {
		segment = strings.ReplaceAll(segment, "~", "~0")
		segment = strings.ReplaceAll(segment, "/", "~1")
		escaped[i] = segment
	}
	return strings.Join(escaped, "/")
}

// writeLinkName writes a reference name bare when the name grammar allows it and single-quoted
// otherwise, so a generated name carrying a `/` reads back as one name.
func writeLinkName(name string) string {
	if name == "" {
		return "''"
	}
	for _, r := range name {
		if !isNameChar(r) {
			return quoteString(name)
		}
	}
	return name
}
