package deon

import (
	"sort"
	"strconv"
	"strings"
)

// Writing a value back to text (specification 12 and 13). Ordinary stringification preserves list and
// final map write order; canonical form sorts every map by code point. The hard requirement is that a
// string is emitted in a form that reads back unchanged, and that two implementations agree on the
// canonical form character for character — so where a shorter form and a safer one both read back, the
// safer one is the form.

func canonical(value Value) string {
	guardDepth(value)
	var b strings.Builder
	writeValue(value, 0, canonicalOpts(), &b)
	b.WriteByte('\n')
	return b.String()
}

func canonicalOpts() StringifyOptions {
	return StringifyOptions{Canonical: true, Readable: true, Indentation: 4, set: true}
}

func stringify(value Value, options StringifyOptions) string {
	guardDepth(value)
	options = options.resolved()

	if options.Leaflinks && !options.Canonical {
		return stringifyWithLeaflinks(value, options)
	}

	var b strings.Builder
	if options.GeneratedHeader {
		b.WriteString("// Generated by Deon.\n\n")
	}
	if options.GeneratedComments {
		b.WriteString("// Root.\n\n")
	}
	writeValue(value, 0, options, &b)
	b.WriteByte('\n')
	return b.String()
}

// stringifyWithLeaflinks is defined in leaflinks.go; declared here as the seam stringify reaches for.

func indentOf(level int, options StringifyOptions) string {
	return strings.Repeat(" ", level*options.Indentation)
}

func writeValue(value Value, level int, options StringifyOptions, b *strings.Builder) {
	switch v := value.(type) {
	case string:
		b.WriteString(writeScalar(v))
	case []Value:
		writeList(v, level, options, b)
	case *Map:
		writeMap(v, level, options, b)
	case *leaflinkRef:
		b.WriteByte('#')
		b.WriteString(writeLinkName(v.name))
	default:
		b.WriteString("''")
	}
}

func writeMap(m *Map, level int, options StringifyOptions, b *strings.Builder) {
	if m.Len() == 0 {
		b.WriteString("{}")
		return
	}

	keys := m.Keys()
	if options.Canonical {
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	}

	if !options.Readable {
		b.WriteByte('{')
		for i, key := range keys {
			if i > 0 {
				b.WriteString(", ")
			}
			writeEntry(m, key, level, options, b)
		}
		b.WriteByte('}')
		return
	}

	b.WriteString("{\n")
	for _, key := range keys {
		b.WriteString(indentOf(level+1, options))
		writeEntry(m, key, level+1, options, b)
		b.WriteByte('\n')
	}
	b.WriteString(indentOf(level, options))
	b.WriteByte('}')
}

func writeEntry(m *Map, key string, level int, options StringifyOptions, b *strings.Builder) {
	value, _ := m.Get(key)

	// A lifted container is written as a link. Shortening emits `#name` alone when the receiving key
	// equals the generated name (specification 12); otherwise the key is written with an explicit link.
	if ref, ok := value.(*leaflinkRef); ok {
		if options.LeaflinkShortening && ref.name == key {
			b.WriteByte('#')
			b.WriteString(writeLinkName(ref.name))
			return
		}
		b.WriteString(writeKey(key))
		b.WriteString(" #")
		b.WriteString(writeLinkName(ref.name))
		return
	}

	b.WriteString(writeKey(key))
	b.WriteByte(' ')
	writeValue(value, level, options, b)
}

func writeList(items []Value, level int, options StringifyOptions, b *strings.Builder) {
	if len(items) == 0 {
		b.WriteString("[]")
		return
	}

	if !options.Readable {
		b.WriteByte('[')
		for i, item := range items {
			if i > 0 {
				b.WriteString(", ")
			}
			writeValue(item, level, options, b)
		}
		b.WriteByte(']')
		return
	}

	b.WriteString("[\n")
	for _, item := range items {
		b.WriteString(indentOf(level+1, options))
		writeValue(item, level+1, options, b)
		b.WriteByte('\n')
	}
	b.WriteString(indentOf(level, options))
	b.WriteByte(']')
}

// #region strings
// writeScalar writes a string in the shortest form that reads back unchanged (specification 12):
// unquoted where it can stand unquoted; a backtick string where it carries a line break and begins and
// ends with a non-whitespace character and has no carriage return; single-quoted otherwise, with its
// line breaks, tabs, and carriage returns written as escapes.
func writeScalar(s string) string {
	if !needsQuote(s) {
		return s
	}
	if useBacktick(s) {
		return backtickForm(s)
	}
	return quoteString(s)
}

// useBacktick reports whether a string that must be quoted is best carried by a backtick string: it
// holds a real line break, which single-quoting would have to escape, and it qualifies for the one
// form that keeps a line break literal (specification 12). A control character other than the line
// break — a carriage return, or any of the set section 4.3 forbids raw — disqualifies it: those have
// no literal form and must be written as `\u{…}` escapes, which only the single-quoted form carries.
func useBacktick(s string) bool {
	if !strings.ContainsRune(s, '\n') || strings.ContainsRune(s, '\r') {
		return false
	}
	runes := []rune(s)
	first, last := runes[0], runes[len(runes)-1]
	if isSpace(first) || first == '\n' || isSpace(last) || last == '\n' {
		return false
	}
	for _, r := range runes {
		if isControl(r) {
			return false
		}
	}
	return true
}

func backtickForm(s string) string {
	var b strings.Builder
	b.WriteByte('`')
	runes := []rune(s)
	for i := 0; i < len(runes); i++ {
		r := runes[i]
		switch {
		case r == '\\':
			b.WriteString("\\\\")
		case r == '`':
			b.WriteString("\\`")
		case r == '#' && i+1 < len(runes) && runes[i+1] == '{':
			b.WriteString("\\#{")
			i++
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('`')
	return b.String()
}

func needsQuote(s string) bool {
	if s == "" {
		return true
	}
	runes := []rune(s)
	first := runes[0]
	last := runes[len(runes)-1]
	if isSpace(first) || isSpace(last) || first == '\n' || last == '\n' {
		return true
	}
	for _, r := range s {
		// Each of these carries structural meaning where a value may begin or continue, so a string
		// holding one does not read back unquoted (specification 12): a bare backslash reads as an
		// escape, a bare tab as separating whitespace, a bracketing delimiter as the edge of a group,
		// a comma or line feed as a separator, and a raw control character as a lexical error. A `#` is
		// quoted wherever it falls — a leading one opens a link, a `...#` a spread, `#{` an
		// interpolation — and even a harmless interior `#` is quoted so two implementations agree on the
		// canonical form (specification 13).
		if isDelimiter(r) || r == ',' || r == '#' || r == '\n' || r == '\r' || r == '\t' || r == '\\' || isControl(r) {
			return true
		}
	}
	if strings.Contains(s, "//") || strings.Contains(s, "/*") {
		return true
	}
	return false
}

func quoteString(s string) string {
	var b strings.Builder
	b.WriteByte('\'')
	runes := []rune(s)
	for i := 0; i < len(runes); i++ {
		r := runes[i]
		switch {
		case r == '\\':
			b.WriteString("\\\\")
		case r == '\'':
			b.WriteString("\\'")
		case r == '\n':
			b.WriteString("\\n")
		case r == '\r':
			b.WriteString("\\r")
		case r == '\t':
			b.WriteString("\\t")
		case r == '#' && i+1 < len(runes) && runes[i+1] == '{':
			b.WriteString("\\#{")
			i++
		case isControl(r):
			// A control character has no literal form: it is written `\u{h}`, its code point in lowercase
			// hexadecimal with no leading zeros (§4.3, §12). Tab, line feed, and carriage return are not
			// controls and keep their `\t`, `\n`, and `\r` spellings, handled above.
			b.WriteString("\\u{")
			b.WriteString(strconv.FormatInt(int64(r), 16))
			b.WriteByte('}')
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('\'')
	return b.String()
}

// writeKey writes a map key: bare when it is a valid name, single-quoted otherwise.
func writeKey(key string) string {
	if key == "" {
		return "''"
	}
	for _, r := range key {
		if !isNameChar(r) {
			return quoteString(key)
		}
	}
	return key
}

// #endregion strings

// guardDepth enforces the nesting limit on a value handed to the stringifier by a host, which never
// met the parser (specification 11.1). It walks iteratively before any recursive writer runs, so the
// limit is checked rather than discovered by a stack overflow.
func guardDepth(value Value) {
	type frame struct {
		value Value
		depth int
	}
	stack := []frame{{value, 0}}
	for len(stack) > 0 {
		f := stack[len(stack)-1]
		stack = stack[:len(stack)-1]
		if f.depth > maxDepth {
			fail(ParseExpected, "The value nests more deeply than the writer will follow.", headSpan("<value>"))
		}
		switch v := f.value.(type) {
		case []Value:
			for _, item := range v {
				stack = append(stack, frame{item, f.depth + 1})
			}
		case *Map:
			for _, key := range v.Keys() {
				member, _ := v.Get(key)
				stack = append(stack, frame{member, f.depth + 1})
			}
		}
	}
}
