package deon;

import java.nio.charset.StandardCharsets;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Deque;
import java.util.List;

/**
 * Writing a value back to text (specification 12 and 13). Ordinary stringification preserves list and
 * final map write order; canonical form sorts every map by code point. A string is emitted in the
 * shortest form that reads back unchanged, and where a shorter form and a safer one both read back, the
 * safer one is the form, so two implementations agree on the canonical text character for character.
 */
final class Stringifier {
    private final StringifyOptions o;
    private final StringBuilder b = new StringBuilder();

    private Stringifier(StringifyOptions options) {
        this.o = options;
    }

    static String stringify(Object value, StringifyOptions options) {
        StringifyOptions o = new StringifyOptions();
        o.canonical = options.canonical;
        o.readable = options.readable;
        o.indentation = options.indentation <= 0 ? 4 : options.indentation;
        o.leaflinks = options.leaflinks;
        o.leaflinkLevel = options.leaflinkLevel;
        o.leaflinkShortening = options.leaflinkShortening;
        o.generatedHeader = options.generatedHeader;
        o.generatedComments = options.generatedComments;

        if (!guardDepth(value)) {
            throw new DeonException(
                    Code.PARSE_EXPECTED,
                    "The value nests more deeply than Deon will write.",
                    Span.head("<value>"));
        }
        return new Stringifier(o).run(value);
    }

    private String run(Object value) {
        if (o.leaflinks && !o.canonical) {
            List<Decl> decls = new ArrayList<>();
            Object root = extract(value, 0, new ArrayList<>(), decls);
            if (o.generatedHeader) {
                b.append("// Generated by Deon.\n\n");
            }
            if (o.generatedComments) {
                b.append("// Root.\n\n");
            }
            writeX(root, 0);
            b.append('\n');
            for (int i = 0; i < decls.size(); i++) {
                b.append('\n');
                if (o.generatedComments && i == 0) {
                    b.append("// Leaflinks.\n\n");
                }
                writeKey(decls.get(i).name);
                b.append(' ');
                writeValue(decls.get(i).value, 0);
                b.append('\n');
            }
            return b.toString();
        }

        if (o.generatedHeader) {
            b.append("// Generated by Deon.\n\n");
        }
        if (o.generatedComments) {
            b.append("// Root.\n\n");
        }
        writeValue(value, 0);
        b.append('\n');
        return b.toString();
    }

    // #region character helpers (delimiters and name characters are ASCII, so char scanning is safe)
    private static boolean space(char c) {
        return c == ' ' || c == '\t';
    }

    private static boolean delim(char c) {
        return switch (c) {
            case '{', '}', '[', ']', '(', ')', '<', '>', '\'', '`' -> true;
            default -> false;
        };
    }

    private static boolean nameChar(char c) {
        return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')
                || (c >= '0' && c <= '9') || c == '_' || c == '-';
    }

    private static boolean needsQuote(String s) {
        if (s.isEmpty()) {
            return true;
        }
        char first = s.charAt(0);
        char last = s.charAt(s.length() - 1);
        if (space(first) || space(last) || first == '\n' || last == '\n') {
            return true;
        }
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            // A '#' anywhere forces a quote (section 12): even where section 4.3 makes it harmless
            // literal text — an interior '#', or a leading one that is not a link — the safer form is the
            // canonical one, so two implementations never disagree about a value's canonical text.
            if (delim(c) || c == '#' || c == ',' || c == '\n' || c == '\r' || c == '\t' || c == '\\') {
                return true;
            }
            if (c == '/' && i + 1 < s.length() && (s.charAt(i + 1) == '/' || s.charAt(i + 1) == '*')) {
                return true;
            }
        }
        return false;
    }

    private static boolean useBacktick(String s) {
        boolean hasNewline = false;
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) == '\n') {
                hasNewline = true;
            }
            if (s.charAt(i) == '\r') {
                return false;
            }
        }
        if (!hasNewline) {
            return false;
        }
        char first = s.charAt(0);
        char last = s.charAt(s.length() - 1);
        return !space(first) && first != '\n' && !space(last) && last != '\n';
    }

    private void quoteString(String s) {
        b.append('\'');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\') {
                b.append("\\\\");
            } else if (c == '\'') {
                b.append("\\'");
            } else if (c == '\n') {
                b.append("\\n");
            } else if (c == '\r') {
                b.append("\\r");
            } else if (c == '\t') {
                b.append("\\t");
            } else if (c == '#' && i + 1 < s.length() && s.charAt(i + 1) == '{') {
                b.append("\\#{");
                i++;
            } else {
                b.append(c);
            }
        }
        b.append('\'');
    }

    private void backtickForm(String s) {
        b.append('`');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\') {
                b.append("\\\\");
            } else if (c == '`') {
                b.append("\\`");
            } else if (c == '#' && i + 1 < s.length() && s.charAt(i + 1) == '{') {
                b.append("\\#{");
                i++;
            } else {
                b.append(c);
            }
        }
        b.append('`');
    }

    private void writeScalar(String s) {
        if (!needsQuote(s)) {
            b.append(s);
        } else if (useBacktick(s)) {
            backtickForm(s);
        } else {
            quoteString(s);
        }
    }

    private void writeKey(String key) {
        if (key.isEmpty()) {
            b.append("''");
            return;
        }
        for (int i = 0; i < key.length(); i++) {
            if (!nameChar(key.charAt(i))) {
                quoteString(key);
                return;
            }
        }
        b.append(key);
    }
    // #endregion

    // #region value writers
    private void indent(int level) {
        b.append(" ".repeat(level * o.indentation));
    }

    /** Canonical order is code-point order, which is UTF-8 byte order — not Java's UTF-16 char order. */
    private static final Comparator<String> CODE_POINT_ORDER = (x, y) -> {
        byte[] bx = x.getBytes(StandardCharsets.UTF_8);
        byte[] by = y.getBytes(StandardCharsets.UTF_8);
        int n = Math.min(bx.length, by.length);
        for (int i = 0; i < n; i++) {
            int cx = bx[i] & 0xff;
            int cy = by[i] & 0xff;
            if (cx != cy) {
                return cx - cy;
            }
        }
        return bx.length - by.length;
    };

    private void writeValue(Object v, int level) {
        if (v instanceof String s) {
            writeScalar(s);
        } else if (v instanceof Boolean bool) {
            b.append(bool ? "true" : "false");
        } else if (v instanceof Double d) {
            if (d == Math.rint(d) && !d.isInfinite()) {
                b.append(Long.toString(d.longValue()));
            } else {
                b.append(d.toString());
            }
        } else if (v instanceof List<?> list) {
            writeList(list, level);
        } else if (v instanceof DeonMap map) {
            writeMap(map, level);
        }
    }

    private void writeMap(DeonMap map, int level) {
        if (map.size() == 0) {
            b.append("{}");
            return;
        }
        List<String> keys = map.keys();
        if (o.canonical) {
            keys.sort(CODE_POINT_ORDER);
        }
        if (!o.readable) {
            b.append('{');
            for (int i = 0; i < keys.size(); i++) {
                if (i > 0) {
                    b.append(", ");
                }
                writeKey(keys.get(i));
                b.append(' ');
                writeValue(map.get(keys.get(i)), level);
            }
            b.append('}');
            return;
        }
        b.append("{\n");
        for (String key : keys) {
            indent(level + 1);
            writeKey(key);
            b.append(' ');
            writeValue(map.get(key), level + 1);
            b.append('\n');
        }
        indent(level);
        b.append('}');
    }

    private void writeList(List<?> list, int level) {
        if (list.isEmpty()) {
            b.append("[]");
            return;
        }
        if (!o.readable) {
            b.append('[');
            for (int i = 0; i < list.size(); i++) {
                if (i > 0) {
                    b.append(", ");
                }
                writeValue(list.get(i), level);
            }
            b.append(']');
            return;
        }
        b.append("[\n");
        for (Object item : list) {
            indent(level + 1);
            writeValue(item, level + 1);
            b.append('\n');
        }
        indent(level);
        b.append(']');
    }
    // #endregion

    // #region leaflinks (section 12)
    private record Decl(String name, Object value) {
    }

    private static final class Ref {
        final String name;

        Ref(String name) {
            this.name = name;
        }
    }

    private static String escapeSegment(String seg) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < seg.length(); i++) {
            char c = seg.charAt(i);
            if (c == '~') {
                out.append("~0");
            } else if (c == '/') {
                out.append("~1");
            } else {
                out.append(c);
            }
        }
        return out.toString();
    }

    private static String leaflinkName(List<String> path) {
        StringBuilder out = new StringBuilder();
        for (int i = 0; i < path.size(); i++) {
            if (i > 0) {
                out.append('/');
            }
            out.append(escapeSegment(path.get(i)));
        }
        return out.toString();
    }

    private Object extract(Object v, int depth, List<String> path, List<Decl> decls) {
        boolean container = v instanceof DeonMap || v instanceof List<?>;
        int level = o.leaflinkLevel < 1 ? 1 : o.leaflinkLevel;
        if (container && depth >= level) {
            String name = leaflinkName(path);
            decls.add(new Decl(name, v));
            return new Ref(name);
        }
        if (v instanceof DeonMap map) {
            DeonMap out = new DeonMap();
            for (String key : map.keys()) {
                List<String> sub = new ArrayList<>(path);
                sub.add(key);
                out.set(key, extract(map.get(key), depth + 1, sub, decls));
            }
            return out;
        }
        if (v instanceof List<?> list) {
            List<Object> out = new ArrayList<>();
            for (int i = 0; i < list.size(); i++) {
                List<String> sub = new ArrayList<>(path);
                sub.add(Integer.toString(i));
                out.add(extract(list.get(i), depth + 1, sub, decls));
            }
            return out;
        }
        return v;
    }

    private void writeX(Object x, int level) {
        if (x instanceof Ref ref) {
            b.append('#');
            writeKey(ref.name);
        } else if (x instanceof DeonMap map) {
            if (map.size() == 0) {
                b.append("{}");
                return;
            }
            b.append("{\n");
            for (String key : map.keys()) {
                indent(level + 1);
                writeXEntry(key, map.get(key), level + 1);
                b.append('\n');
            }
            indent(level);
            b.append('}');
        } else if (x instanceof List<?> list) {
            if (list.isEmpty()) {
                b.append("[]");
                return;
            }
            b.append("[\n");
            for (Object item : list) {
                indent(level + 1);
                writeX(item, level + 1);
                b.append('\n');
            }
            indent(level);
            b.append(']');
        } else {
            writeValue(x, level);
        }
    }

    private void writeXEntry(String key, Object val, int level) {
        if (val instanceof Ref ref) {
            if (o.leaflinkShortening && ref.name.equals(key)) {
                b.append('#');
                writeKey(ref.name);
                return;
            }
            writeKey(key);
            b.append(" #");
            writeKey(ref.name);
            return;
        }
        writeKey(key);
        b.append(' ');
        writeX(val, level);
    }
    // #endregion

    /** Enforce the nesting limit on a host-built value the parser never met (specification 11.1). */
    private static boolean guardDepth(Object root) {
        record Frame(Object value, int depth) {
        }
        Deque<Frame> stack = new ArrayDeque<>();
        stack.push(new Frame(root, 0));
        while (!stack.isEmpty()) {
            Frame f = stack.pop();
            if (f.depth() > Parser.MAX_DEPTH) {
                return false;
            }
            if (f.value() instanceof List<?> list) {
                for (Object item : list) {
                    stack.push(new Frame(item, f.depth() + 1));
                }
            } else if (f.value() instanceof DeonMap map) {
                for (String key : map.keys()) {
                    stack.push(new Frame(map.get(key), f.depth() + 1));
                }
            }
        }
        return true;
    }
}
