//! A value back into source (specification 12).

use crate::options::StringifyOptions;
use crate::text::{is_bare_name, is_unsafe_scalar};
use crate::value::Value;

/// What is actually written out: a value, or a leaflink standing in for one that was lifted out of
/// the root. The data model has no link in it, so the extraction needs a shape of its own rather
/// than a string that means something else.
enum Node {
    String(String),
    List(Vec<Node>),
    Map(Vec<(String, Node)>),
    Link(String),
}

impl Node {
    fn of(value: &Value) -> Self {
        match value {
            Value::String(text) => Node::String(text.clone()),
            Value::List(items) => Node::List(items.iter().map(Node::of).collect()),
            Value::Map(entries) => Node::Map(
                entries
                    .iter()
                    .map(|(key, entry)| (key.clone(), Node::of(entry)))
                    .collect(),
            ),
        }
    }
}

struct Generated {
    name: String,
    value: Value,
}

/// The backslash is doubled before any escape is introduced, or the backslash of that escape would
/// itself be doubled.
fn escape_shared(value: &str) -> String {
    value.replace('\\', "\\\\").replace("#{", "\\#{")
}

/// A singlequoted string cannot cross a newline, so its line breaks are written as escapes. Unlike a
/// backticked string, it keeps the whitespace at its boundaries exactly as it is given.
fn quoted(value: &str) -> String {
    let escaped = escape_shared(value)
        .replace('\'', "\\'")
        .replace('\r', "\\r")
        .replace('\n', "\\n")
        .replace('\t', "\\t");

    format!("'{escaped}'")
}

/// A backticked string trims the whitespace at its boundaries, so it can only hold a value that has
/// none. Anything else would come back shorter than it went in.
fn multiline(value: &str) -> String {
    format!("`{}`", escape_shared(value).replace('`', "\\`"))
}

/// Writes a string in the shortest form that reads back unchanged.
///
/// Backticks can hold a laid-out value only when nothing at its boundaries would be trimmed away,
/// and only when it carries no carriage return, which the source normalization would fold into the
/// line ending. Everything else is singlequoted, where an escape says precisely what is meant.
fn scalar(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }

    let bounded = value != value.trim();

    if value.contains('\n') && !bounded && !value.contains('\r') {
        return multiline(value);
    }

    if bounded || value.contains(['\n', '\r', '\t']) || is_unsafe_scalar(value) {
        return quoted(value);
    }

    value.to_string()
}

fn name(value: &str) -> String {
    if is_bare_name(value) {
        value.to_string()
    } else {
        quoted(value)
    }
}

/// The root-relative path of a generated leaflink, `~` written as `~0` and `/` as `~1` so that the
/// segments can be joined by `/` without ambiguity.
fn path_name(segments: &[String]) -> String {
    segments
        .iter()
        .map(|segment| segment.replace('~', "~0").replace('/', "~1"))
        .collect::<Vec<_>>()
        .join("/")
}

pub struct Stringifier {
    options: StringifyOptions,
    indentation: String,
}

impl Stringifier {
    pub fn new(options: StringifyOptions) -> Self {
        let options = options.resolved();
        let indentation = " ".repeat(options.indentation);

        Self {
            options,
            indentation,
        }
    }

    pub fn stringify(&self, value: &Value) -> String {
        let mut leaflinks: Vec<Generated> = Vec::new();

        let root = if self.options.leaflinks && self.options.leaflink_level >= 1 {
            self.extract(value, &mut Vec::new(), 0, &mut leaflinks)
        } else {
            Node::of(value)
        };

        let mut sections: Vec<String> = Vec::new();

        if self.options.generated_header {
            sections.push("// Generated by Deon.".to_string());
        }

        if self.options.generated_comments {
            sections.push("// Root.".to_string());
        }

        sections.push(self.node(&root, 0));

        if !leaflinks.is_empty() {
            if self.options.generated_comments {
                sections.push("// Leaflinks.".to_string());
            }

            sections.push(
                leaflinks
                    .iter()
                    .map(|leaflink| {
                        format!(
                            "{} {}",
                            name(&leaflink.name),
                            self.node(&Node::of(&leaflink.value), 0),
                        )
                    })
                    .collect::<Vec<_>>()
                    .join("\n\n"),
            );
        }

        let body = sections.join("\n\n");

        format!("{}\n", body.trim_end_matches('\n'))
    }

    /// Lifts the containers sitting exactly at `leaflink_level` out of the root and into
    /// declarations of their own. Once an ancestor is lifted, its descendants travel with it.
    fn extract(
        &self,
        value: &Value,
        path: &mut Vec<String>,
        level: usize,
        leaflinks: &mut Vec<Generated>,
    ) -> Node {
        if !value.is_container() {
            return Node::of(value);
        }

        if level == self.options.leaflink_level {
            let generated = path_name(path);

            leaflinks.push(Generated {
                name: generated.clone(),
                value: value.clone(),
            });

            return Node::Link(generated);
        }

        match value {
            Value::List(items) => Node::List(
                items
                    .iter()
                    .enumerate()
                    .map(|(index, item)| {
                        path.push(index.to_string());
                        let extracted = self.extract(item, path, level + 1, leaflinks);
                        path.pop();

                        extracted
                    })
                    .collect(),
            ),
            Value::Map(entries) => Node::Map(
                entries
                    .iter()
                    .map(|(key, entry)| {
                        path.push(key.clone());
                        let extracted = self.extract(entry, path, level + 1, leaflinks);
                        path.pop();

                        (key.clone(), extracted)
                    })
                    .collect(),
            ),
            Value::String(text) => Node::String(text.clone()),
        }
    }

    fn node(&self, node: &Node, level: usize) -> String {
        match node {
            Node::Link(link) => format!("#{}", name(link)),
            Node::String(text) => scalar(text),
            Node::List(items) => self.list(items, level),
            Node::Map(entries) => self.map(entries, level),
        }
    }

    fn map(&self, entries: &[(String, Node)], level: usize) -> String {
        if entries.is_empty() {
            return "{}".to_string();
        }

        let mut order: Vec<&(String, Node)> = entries.iter().collect();

        // Canonical output sorts map keys by code point — which, for UTF-8, byte order already is —
        // and never by the host's locale.
        if self.options.canonical {
            order.sort_unstable_by(|left, right| left.0.cmp(&right.0));
        }

        let written: Vec<String> = order
            .iter()
            .map(|(key, entry)| {
                // The shortened form is only written when the receiving key is the name of the
                // leaflink.
                if let Node::Link(link) = entry {
                    if self.options.leaflink_shortening && link == key {
                        return format!("#{}", name(link));
                    }
                }

                format!("{} {}", name(key), self.node(entry, level + 1))
            })
            .collect();

        self.group('{', '}', &written, level)
    }

    fn list(&self, items: &[Node], level: usize) -> String {
        if items.is_empty() {
            return "[]".to_string();
        }

        let written: Vec<String> = items
            .iter()
            .map(|item| self.node(item, level + 1))
            .collect();

        self.group('[', ']', &written, level)
    }

    /// Readable output lays each entry on its own line. Otherwise the entries are separated by the
    /// comma, which the grammar accepts wherever it accepts a newline.
    fn group(&self, open: char, close: char, entries: &[String], level: usize) -> String {
        if !self.options.readable {
            return format!("{open}{}{close}", entries.join(", "));
        }

        let indent = self.indentation.repeat(level + 1);
        let closing = self.indentation.repeat(level);

        let body = entries
            .iter()
            .map(|entry| format!("{indent}{entry}"))
            .collect::<Vec<_>>()
            .join("\n");

        format!("{open}\n{body}\n{closing}{close}")
    }
}
